services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: offkai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports: ["5432:5432"]

  app:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/offkai
    volumes:
      - .:/workspace
    ports: ["3000:3000", "5173:5173"]
    depends_on: [db]
    security_opt:
      - seccomp=unconfined

volumes:
  db_data:
